# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=30)),
                ('item_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('item_category', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(blank=True, default='', null=True)),
                ('hardware', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_item', models.ImageField(upload_to='img/photo')),
                ('particular', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.Item')),
            ],
        ),
        migrations.AddField(
            model_name='look',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.Service'),
        ),
        migrations.AddField(
            model_name='look',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.Item'),
        ),
    ]
