# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
